spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: jianer
      password: jianer
