server.port: 8889

spring:
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: localhost
#    手工确认消息已到达交换机
    publisher-returns: true
#    确认消息已到达队列
    publisher-confirm-type: correlated

