spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eesy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml